---
title: "Homework 8"
subtitle: "MATH/STAT 394"
author: "WRITE YOUR NAME HERE"
output: pdf_document
header-includes:
    - \usepackage{amsmath, amssymb}
    - \usepackage{setspace} 
---
\onehalfspacing

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
#R packages
library(tidyverse)  

```

* * * 

### Instructions

- This homework is due in Gradescope on Wednesday Dec 3 by midnight PST. There is a 15 minute grace period and submissions made during this time will not be marked as late. \textbf{There are no late days on this homework and work submitted after this deadline will not be graded}.  

- Please answer the following questions in the order in which they are posed. \textbf{Be sure to support your work and show your steps. All calculations must be done within your document and shown with the answer printed}

- Don't forget to (i) make a local copy this document for your work and to (ii) knit the document frequently to make sure there are no compilation errors. 

- When you are done, download the PDF file as instructed in section and submit it in Gradescope. \textbf{Do not forget to tag your answers to every sub-part of every question. We will take off 10\% for every part that is not tagged}

- \textbf{Please read the acceptable policies for this class in CANVAS. In particular, you are NOT ALLOWED to consult external sources - AI, tutors, tutoring sites, internet - to complete any part of this work. Do not use notation or definitions or results we have not covered in this class. We will deduct points for this. }

* * *


### Exercises 

1. (Unif) Suppose $X \sim Unif(0,1)$. That is, it has PDF $f(x) = 1 \quad 0 \leq x < 1$ and CDF
$$F_{X}(x) = \begin{cases} 
               0 & x < 0 \\
               x & 0 \leq x < 1 \\
               1 & x \geq 1 \end{cases}$$
               

a. Let $Y = X^{n}$ where $n$ is a positive integer. Find $F_{Y}(y)$ the CDF of $Y$.

b. Find a PDF for $Y$. Don't forget to show your steps and any rules you are using.

c. Find $E\left[Y \right]$ in two ways: one using the PDF of $X$ and the other using the PDF of $Y$.

2. (Tool-and-die) A tool-and-die company makes castings for steel stress-monitoring gauges. Their annual profit $Q$ is a function of demand $X$, given by $$t(X) = 1 - e^{-2 X}.$$
Suppose the demand $X$ has the PDF $$f(x) = 6 e^{-6x} \ \ \   x \geq 0.$$ Find their expected profit. State any rules you use and show your work clearly. 

3. (Jam) A company produces jam in cardboard containers. An empty box weighs 1.5 ounces. They fill a container by putting it on a scale and filling in jam until the scale shows a weight of $m$ ounces. The scale has a measurement error, so the actual amount of jam in the container - $X$ - is normally distributed with mean $\mu = m-1.5$ ounces and standard deviation $\sigma = 0.25$ ounces

    How should the company choose $m$ so that 95\% of the jars contain at least 16 ounces of jam.

    Note: be sure to show your steps, also any code and output.
    


4. (Ball bearings) The diameters (in mm) of ball bearings from a particular company are normally distributed. In order to quickly determine the parameters of the normal distribution, one determines the proportion of ball bearings going through sieves with circular holes of different sizes. If 23% of the bearings go through a hole of diameter 4.9 mm and 59% go through a hole of diameter 5.0 mm, what are the mean and standard deviation of the normal distribution? Assume the ball bearings are spherical. 

    Note: Be sure to show all steps, and anycode and output to solve the equations.

    *Hint:* Let $X$ denote the diameter of a randomly selected ball bearing. Then $X \sim Norm(\mu, \sigma)$. You are given
\begin{align*}
P(X \leq 4.9) &= 0.23,\\
P(X \leq 5.0) &= 0.59.
\end{align*}



